### ISSUE TITLE
improve performance by tuning the release profile

### ISSUE THREAD

**Issue by CommanderStorm** [bbox-services/bbox#100]
I have not measured what the performance impact for bbox is.
You might be able to tune performance in the release profile:

```toml
[profile.release]
# Make release binaries a bit smaller
lto = true
codegen-units = 1
```

Concrete performance impact is likely to be low, but maybe a few percent
