### ISSUE TITLE
Custom grids for higher zoom levels (up to 42)?

### ISSUE THREAD

**Issue by simonpenel** [bbox-services/bbox#58]
Hello,
thanks Pirmin for  your answer at  the issue initially posted dhere

https://github.com/t-rex-tileserver/t-rex/issues/316

          Hi Pirmin,  
First, thanks a lot for your help. And sorry for this long message. We tried with @simonpenel to prepare a small example showing the bug we are facing when zooming in the map, and for which we are struggling finding a solution. If it is obvious for you what happens an how to solve it, it would be great !  

**The symptom** : if you zoom in the simple map (only black) we prepared at this url: http://134.214.213.45/assets/html/index_test42.html, you will see that starting from zoom 27, some tiles do not display correctly, creating some kind of irregular checkerboard
![image](https://github.com/t-rex-tileserver/t-rex/assets/15011328/5c0654b9-e115-4972-bdc0-a41fd6a37c5e)

**The reproducible example**: To make the problem very simple and easily reproducible we decided that the map only displays one tile (always the same, named 1.pbf). 
The server configuration file was this one this one : 
```toml
[[datasource]]
#will not be used 
name = "gebco"
[datasource.wms_proxy]
baseurl = "https://www.gebco.net/data_and_products/gebco_web_services/web_map_service/mapserv?version=1.3.0"
format = "image/jpeg"


[[assets.static]]
dir = "./assets"
path = "/assets"

[[tilestore]]
name = "tilecache"    
[tilestore.files]
#base_dir = "../tiles"
base_dir = "/tmp/mvtbench"

[[tilestore]]
name = "mbtilecache"
[tilestore.mbtiles]
path = "/tmp/tilecache.mbtiles"

[[tilestore]]
name = "pmtilecache"
[tilestore.pmtiles]
path = "/tmp/tilecache.pmtiles"

[[tileset]]
name = "gebco"
wms_proxy = { source = "gebco", layers = "gebco_latest" }
```
and the configuration json files used are available here: 
[mystyle_test42.json](https://github.com/t-rex-tileserver/t-rex/files/14942831/mystyle_test42.json)
[lines_test42.json](https://github.com/t-rex-tileserver/t-rex/files/14942832/lines_test42.json)

Do you have any idea where the problem could come from?

All the best, and thanks again for your time, 

Damien

_Originally posted by @damiendevienne in https://github.com/t-rex-tileserver/t-rex/issues/316#issuecomment-2049110387_
