### ISSUE TITLE
Unable to expose tables from non-public schemas in BBOX

### ISSUE THREAD

**Issue by FabianRechsteiner** [bbox-services/bbox#91]
**Description:**

I am using BBOX as a Docker container and have the following bbox.toml configuration defined for the collections:

```toml
# -- Feature-Server --
# -- datasources --
[[datasource]]
name = "postgres"
[datasource.postgis]
url = "postgresql://@postgis/" #postgresql://user_name:user_password@postgis/postgres_db

# -- collections with auto discovery --
[[collections.postgis]]
url = "postgresql://@postgis/" #postgresql://user_name:user_password@postgis/postgres_db
[[collections.directory]]
dir = "/assets"
```
In the Docker Compose file, I pass the following PostGIS parameters:

- `POSTGRES_BBOX_USERNAME`
- `POSTGRES_BBOX_PASSWORD`
- `POSTGRES_DB`
- `POSTGRES_HOST`

For the BBOX server, I created a new user `bbox` in the PostGIS database, which has read-only access to selected tables and schemas.

BBOX automatically recognizes tables in the `public` schema, where the user has read access, and creates collections from them. However, it seems not possible to expose tables from other schemas, such as `kommunaler_richtplan`, even though the user has read access to the schema and all its tables.

There doesn't seem to be a `SCHEMA` parameter available. It might be useful to allow BBOX to support multiple schemas, possibly by accepting an array to configure which schemas to include.

**Question:** How can I expose tables from the kommunaler_richtplan schema and others in BBOX as collections?

**Possible Feature Request:** It would be beneficial if BBOX could accept an array of schemas in the configuration file, enabling the exposure of tables from multiple schemas, not just `public`.

**Comment by kdesjard** [comment]
Are you able to test the pg_schemas branch from the following repo to see if it works for you?

https://github.com/kdesjard/bbox.git

You could then do:

```toml
# -- Feature-Server --
# -- datasources --
[[datasource]]
name = "postgres"
[datasource.postgis]
url = "postgresql://@postgis/" #postgresql://user_name:user_password@postgis/postgres_db

# -- collections with auto discovery --
[[collections.postgis]]
url = "postgresql://@postgis/" #postgresql://user_name:user_password@postgis/postgres_db
search_path = ["public","kommunaler_richtplan"]
[[collections.directory]]
dir = "/assets"
```
